# line.yaml

out_dir: results
metric_best: acc
cfg_dest: vgae.yaml
print: file


wandb:
  use: True
  project: gtblueprint
  name_tag: vgae-cora-origin

train:
  mode: custom
  batch_size: 32   
  eval_period: 1
  epochs: 2000
  
model:
  type: vgae
  out_channels: 16
  hidden_channels: 8  # Assume that the dimension of the hidden layer feature is 8
    
num_threads: 11

data:
  name: cora
  undirected: True
  include_negatives: True
  val_pct: 0.15
  test_pct: 0.05
  split_labels: True
  num_features:  1433

