wandb_version: 1

embed_size:
  value: 57
iter:
  value: 1
num_neg_samples:
  value: 5
num_walks:
  value: 40
p:
  value: 0.9255496358171692
q:
  value: 0.41529458110195816
walk_length:
  value: 15
window_size:
  value: 9
ws:
  value: 9
