wandb_version: 1

embed_size:
  value: 56
iter:
  value: 1
num_neg_samples:
  value: 5
num_walks:
  value: 60
p:
  value: 0.9145324773822434
q:
  value: 0.7053666848456641
walk_length:
  value: 15
window_size:
  value: 10
ws:
  value: 11
