wandb_version: 1

embed_size:
  value: 104
iter:
  value: 3
num_neg_samples:
  value: 3
num_walks:
  value: 80
p:
  value: 0.8243052608921403
q:
  value: 0.3083061532234769
walk_length:
  value: 27
window_size:
  value: 8
ws:
  value: 3
