wandb_version: 1

embed_size:
  value: 63
iter:
  value: 7
num_neg_samples:
  value: 5
num_walks:
  value: 60
p:
  value: 0.8402467725211601
q:
  value: 0.6490627573443615
walk_length:
  value: 9
window_size:
  value: 2
ws:
  value: 7
