wandb_version: 1

embed_size:
  value: 44
iter:
  value: 3
num_neg_samples:
  value: 5
num_walks:
  value: 40
p:
  value: 0.9135569024737472
q:
  value: 0.45294519357358265
walk_length:
  value: 17
window_size:
  value: 9
ws:
  value: 3
