wandb_version: 1

embed_size:
  value: 113
iter:
  value: 1
num_walks:
  value: 60
p:
  value: 0.6949228255789311
q:
  value: 0.6649859690329807
walk_length:
  value: 27
window_size:
  value: 7
ws:
  value: 9
