wandb_version: 1

embed_size:
  value: 51
iter:
  value: 1
num_walks:
  value: 40
p:
  value: 0.2605319969166913
q:
  value: 0.5127262582161032
walk_length:
  value: 22
window_size:
  value: 3
ws:
  value: 9
