wandb_version: 1

embed_size:
  value: 119
iter:
  value: 1
num_neg_samples:
  value: 3
num_walks:
  value: 40
p:
  value: 0.37507571966435216
q:
  value: 0.27548085684618046
walk_length:
  value: 13
window_size:
  value: 7
ws:
  value: 3
