wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/core/Embedding/wb_tune.py
    python_version: 3.8.17
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709402020.59047
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 77
      3:
      - 2
      - 23
      - 37
      4: 3.8.17
      5: 0.16.3
      6: 4.31.0
      8:
      - 5
      13: linux-x86_64
embed_size:
  desc: null
  value: 116
iter:
  desc: null
  value: 1
num_neg_samples:
  desc: null
  value: 3
num_walks:
  desc: null
  value: 60
p:
  desc: null
  value: 1.7289951779946364
q:
  desc: null
  value: 4.475282720400136
walk_length:
  desc: null
  value: 17
window_size:
  desc: null
  value: 3
ws:
  desc: null
  value: 5
