# line.yaml

out_dir: results
metric_best: acc
wandb:
  use: True
  project: gtblueprint

train:
  mode: custom
  batch_size: 32   
  eval_period: 1
  epochs: 2000
  
model:
  type: GAT
  in_channels: 12
  out_channels: 16
  heads: 4
  hidden_channels: 8  # Assume that the dimension of the hidden layer feature is 8
  negative_slope: 0.2
  dropout: 0
  num_layers: 2
  heads: 4
  
num_threads: 11

data:
  name: cora
  undirected: True
  include_negatives: True
  val_pct: 0.15
  test_pct: 0.05
  split_labels: False
  num_features:  1433

