# line.yaml

out_dir: results
metric_best: acc
wandb:
  use: True
  project: gtblueprint

train:
  mode: custom
  batch_size: 32   
  eval_period: 1
  epochs: 2000
  
model:
  type: graphsage
  in_channels: 12
  out_channels: 16
    
num_threads: 11

data:
  name: cora
  undirected: True
  include_negatives: True
  val_pct: 0.15
  test_pct: 0.05
  split_labels: True
  num_features:  1433

