wandb_version: 1

embed_size:
  value: 45
iter:
  value: 1
num_neg_samples:
  value: 5
num_walks:
  value: 60
p:
  value: 0.7680237209914716
q:
  value: 0.14081372177522208
walk_length:
  value: 5
window_size:
  value: 10
ws:
  value: 3
