wandb_version: 1

embed_size:
  value: 95
iter:
  value: 1
num_walks:
  value: 80
p:
  value: 0.13441092285347217
q:
  value: 0.2414313145336616
walk_length:
  value: 21
window_size:
  value: 7
ws:
  value: 3
