wandb_version: 1

embed_size:
  value: 118
iter:
  value: 3
num_neg_samples:
  value: 5
num_walks:
  value: 80
p:
  value: 4.32584612369039
q:
  value: 1.2691063488768322
walk_length:
  value: 6
window_size:
  value: 9
ws:
  value: 3
