wandb_version: 1

embed_size:
  value: 94
iter:
  value: 1
num_neg_samples:
  value: 3
num_walks:
  value: 60
p:
  value: 0.15202117784194374
q:
  value: 2.179282232887916
walk_length:
  value: 19
window_size:
  value: 6
ws:
  value: 7
