# line.yaml

out_dir: results
metric_best: acc
cfg_dest: gsaint.yaml
print: file
seed: 0

run:
  seed: 0
  num_threads: 11
  multiple_splits: None

wandb:
  use: True
  project: gtblueprint
  name_tag: gsaint-arxiv_2023-origin

train:
  mode: custom
  batch_size: 32   
  eval_period: 1
  epochs: 2000
  auto_resume: False
  lr: 0.01

model:
  type: gsaint_gae
  out_channels: 16
  hidden_channels: 8  # Assume that the dimension of the hidden layer feature is 8
  in_channels: 500 # Missed! AttrubuteError
    
num_threads: 11

data:
  name: pubmed
  undirected: True
  device: 0 
  include_negatives: True
  val_pct: 0.15
  test_pct: 0.05
  split_labels: True
  num_features: 500
  split_index: [0.8, 0.15, 0.05]

optimizer:
  type: adam
  base_lr: 0.01
  weight_decay: 0.0005
