wandb_version: 1

embed_size:
  value: 99
iter:
  value: 1
num_neg_samples:
  value: 3
num_walks:
  value: 80
p:
  value: 0.9605811918662008
q:
  value: 0.8254032734974976
walk_length:
  value: 7
window_size:
  value: 4
ws:
  value: 3
