wandb_version: 1

embed_size:
  value: 75
iter:
  value: 1
num_walks:
  value: 60
p:
  value: 0.5545918212262221
q:
  value: 0.6370138346669741
walk_length:
  value: 28
window_size:
  value: 3
ws:
  value: 11
