wandb_version: 1

embed_size:
  value: 58
iter:
  value: 7
num_walks:
  value: 80
p:
  value: 0.5226974848468255
q:
  value: 0.2228840427716247
walk_length:
  value: 16
window_size:
  value: 4
ws:
  value: 11
