wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/core/Embedding/wb_tune.py
    python_version: 3.8.17
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709367717.230291
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 53
      - 55
      - 77
      3:
      - 23
      4: 3.8.17
      5: 0.16.3
      6: 4.31.0
      8:
      - 5
      13: linux-x86_64
embed_size:
  desc: null
  value: 99
iter:
  desc: null
  value: 1
num_neg_samples:
  desc: null
  value: 3
num_walks:
  desc: null
  value: 80
p:
  desc: null
  value: 0.9605811918662008
q:
  desc: null
  value: 0.8254032734974976
walk_length:
  desc: null
  value: 7
window_size:
  desc: null
  value: 4
ws:
  desc: null
  value: 3
