wandb_version: 1

embed_size:
  value: 61
iter:
  value: 1
num_neg_samples:
  value: 5
num_walks:
  value: 80
p:
  value: 0.8367458671481132
q:
  value: 0.6537846142438363
walk_length:
  value: 28
window_size:
  value: 9
ws:
  value: 3
