wandb_version: 1

embed_size:
  value: 33
iter:
  value: 3
num_neg_samples:
  value: 1
num_walks:
  value: 60
p:
  value: 0.3539854945531843
q:
  value: 0.922420773169334
walk_length:
  value: 13
window_size:
  value: 9
ws:
  value: 7
