wandb_version: 1

embed_size:
  value: 93
iter:
  value: 7
num_neg_samples:
  value: 3
num_walks:
  value: 40
p:
  value: 0.30333143603538965
q:
  value: 0.2467026019717486
walk_length:
  value: 30
window_size:
  value: 6
ws:
  value: 11
